### ISSUE TITLE
Throw when adding redundant Effect to Event

### ISSUE THREAD

**Issue by bhwithun** [CalvinTheRed/DNDEngine#5]
for example:

``` Java
public void grantDisadvantage(Effect e) throws Exception {
    if (isEffectApplied(e)) throw new Exception("Effect already applied");
    disadvantage++;
    applyEffect(e);
}
```

**Comment by CalvinTheRed** [comment]
Throwing an exception will work best if thrown at the level of `Event.applyEffect()`. This way, not every modifier function like `grantDisadvantage()`, `grantAdvantage()`, etc, will all have to throw their own exceptions - they just throw the exception from when they call `applyEffect()`, and this exception will be handled at the level of the Effect trying to modify the Event.

The consequence of this is that no single Effect may both grant advantage and, say, an attack roll bonus, to the same Event at the same time, but I do not believe there are any such use cases to be concerned about.
